package com.basinity.challengex.core.registry;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Writes the web builder's catalog. Driven by the {@code exportCatalog} Gradle
 * task.
 *
 * <p>The catalog ships as a script assigning a global rather than as a bare
 * {@code .json} file: the site is static and client-side only, and a browser
 * refuses to {@code fetch} a sibling file over {@code file://}. Emitting it as
 * a script means the whole site opens straight off disk with no server and
 * makes no requests at all, which is the constraint the site is built under.
 * The document inside the assignment is exactly what {@link CatalogJson}
 * produces.
 */
public final class CatalogExportMain {

    private static final String HEADER = """
            // Generated by the :core:exportCatalog Gradle task from the core registries.
            // Do not edit by hand: rerun the task after changing a catalog entry.
            window.CX_CATALOG =\s""";

    private CatalogExportMain() {
    }

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            throw new IllegalArgumentException("usage: CatalogExportMain <output-file>");
        }
        Path target = Path.of(args[0]);
        Files.createDirectories(target.toAbsolutePath().getParent());
        String catalog = CatalogJson.of(CoreCatalog.createRegistries()).stripTrailing();
        Files.writeString(target, HEADER + catalog + ";\n", StandardCharsets.UTF_8);
        System.out.println("Wrote catalog to " + target.toAbsolutePath());
    }
}
