pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'dev.kikugie.stonecutter' version '0.9.8'
}

rootProject.name = 'ChallengeX'

include 'core'
include 'common'

stonecutter {
    kotlinController = false
    centralScript = 'build.gradle'

    create(getRootProject()) {
        branch('fabric') {
            versions '26.2', '26.3'
        }
        branch('paper') {
            versions '26.2', '26.3'
        }
    }
}
