pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'dev.kikugie.stonecutter' version '0.9.8'
}

rootProject.name = 'ChallengeX'

include 'core'
include 'common'

stonecutter {
    kotlinController = false
    centralScript = 'build.gradle'

    create(getRootProject()) {
        ['fabric', 'paper'].each { loader ->
            branch(loader) {
                versions '26.2', '26.3'
            }
        }
    }
}
