package com.basinity.challengex.common.support;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.util.Set;
import java.util.TreeSet;

/**
 * Serializes {@link PlatformSupport} into the file the website reads. Ships as
 * a script assigning a global rather than as JSON, for the same reason the
 * catalog does: a browser refuses to fetch a sibling file over {@code file://},
 * and the site is built to open straight off disk.
 */
public final class SupportJson {

    private SupportJson() {
    }

    public static String write() {
        JsonObject root = new JsonObject();
        root.addProperty("supportVersion", PlatformSupport.SUPPORT_VERSION);

        JsonArray platforms = new JsonArray();
        JsonObject unsupported = new JsonObject();
        for (String platform : PlatformSupport.platforms()) {
            platforms.add(platform);
            JsonArray ids = new JsonArray();
            // Sorted, so a rebuild that changes nothing leaves the file byte
            // for byte identical and never shows up as a diff.
            for (String id : new TreeSet<>(PlatformSupport.unsupportedOn(platform))) {
                ids.add(id);
            }
            unsupported.add(platform, ids);
        }
        root.add("platforms", platforms);
        root.add("unsupported", unsupported);

        String json = new GsonBuilder().setPrettyPrinting().create().toJson(root);
        return """
                /* Generated by ./gradlew :common:exportSupport. Do not edit by hand.

                   Which catalog entries each platform does not run. The builder marks
                   them and the share page says so; nothing here ever blocks an export,
                   the same as every other thing the site knows and does not enforce. */

                window.CX_SUPPORT = %s;
                """.formatted(json);
    }

    /** Every id named across all platforms, for a test to hold against the catalog. */
    public static Set<String> allNamedIds() {
        Set<String> ids = new TreeSet<>();
        for (String platform : PlatformSupport.platforms()) {
            ids.addAll(PlatformSupport.unsupportedOn(platform));
        }
        return ids;
    }
}
